version: '3.9'

services: 
    
    db:
        image: mongo
        restart: 'unless-stopped'
        container_name: mongo_compose
        ports: 
            - '27018:27017'
        volumes: 
            - ~/mongo/data:/data/db
        networks: 
            - app

    dbms:
        image: mongo-express
        restart: 'unless-stopped'
        ports: 
            - '8081:8081'
        container_name: mexpress_compose
        networks:
            - app
        depends_on: 
            - db
        environment: 
            ME_CONFIG_MONGODB_SERVER: db
            ME_CONFIG_BASICAUTH_USERNAME: DASistemas
            ME_CONFIG_BASICAUTH_PASSWORD: ex-especial567

    mapper:
        build: ./mapper
        depends_on: 
            - db
        networks: 
            - app
        command: go run ./app.go

    api:
        build: ./api
        restart: 'unless-stopped'
        container_name: api
        ports: 
            - '7777:3000'
        networks: 
            - app
        command: go run .


networks:
    app: